version: '3'
services:
  front:
    build: ./front
    ports:
      - "3002:3000"
    environment:
      - NUXT_PUBLIC_API_URL="http://back:3000/"

  back:
    build : ./back
    ports:
      - "3000:3000"
