version: '3'
services:
  front:
    build: ./front
    ports:
      - "3002:3000"
    environment:
      - NUXT_PUBLIC_API_URL="http://localhost:3000/"
    networks:
      - app

  back:
    build : ./back
    ports:
      - "3000:3000"
    networks:
      - app

networks:
  app:
    driver: bridge